<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Guillaume Pain" />

<meta name="date" content="2022-09-03" />

<title>Practical 4</title>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Guillaume Pain Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="practical1.html">Practical 1</a>
</li>
<li>
  <a href="practical2.html">Practical 2</a>
</li>
<li>
  <a href="practical3.html">Practical 3</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Practical 4</h1>
<h4 class="author">Guillaume Pain</h4>
<h4 class="date">09/03/2022</h4>

</div>


<pre class="r"><code>my_data &lt;-read.csv2(&quot;plasma.csv&quot;)
my_data$group&lt;-as.factor(my_data$group)</code></pre>
<p>Today we aim to perform statistical tests on the dataset we have at our disposal.</p>
<p><span class="math inline">\(\huge{First \ \ step :}\)</span></p>
<p>We will see whether the concentration of citrate in plasma changes significantly over time.</p>
<p>Difference between 8am and 11am</p>
<p><span class="math inline">\(\\\)</span> We perform a student’s test :</p>
<pre class="r"><code>test_1&lt;-t.test(my_data$X11am-my_data$X8am)

pvalues&lt;-test_1$p.value
mean(my_data$X11am-my_data$X8am)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>round(pvalues,3)</code></pre>
<pre><code>## [1] 0.096</code></pre>
<p>On average, consentration increased by 9.4</p>
<p>At the risk of being wrong at 9.6%, the change in concentration between the two hours has significantly increased.</p>
<p>Difference between 11am and 3pm</p>
<p><span class="math inline">\(\\\)</span> We perform a student’s test :</p>
<pre class="r"><code>test_2&lt;-t.test(my_data$X3pm-my_data$X11am)

pvalues_2&lt;-test_2$p.value
mean(my_data$X3pm-my_data$X11am)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>round(pvalues_2,3)</code></pre>
<pre><code>## [1] 0.013</code></pre>
<p>On average, consentration decreased by 15.3</p>
<p>At the risk of being wrong at 1.3%, the change in concentration between the two hours has significantly decreased.</p>
<p><span class="math inline">\(\huge{Second \ \ step :}\)</span></p>
<p>Difference between two groups</p>
<pre class="r"><code>library(plyr)    
library(ggplot2)</code></pre>
<pre class="r"><code>GenderPlot1_FLIP = ggplot(my_data, aes(x = group, y = X8am)) + geom_boxplot() + coord_flip()
GenderPlot1_FLIP </code></pre>
<pre><code>## Warning: Removed 4 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="practical4_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Group 1 seems to have a higher average.</p>
<p>Let’s do a test to be sure</p>
<pre class="r"><code>library(&quot;dplyr&quot;)</code></pre>
<pre><code>## 
## Attachement du package : &#39;dplyr&#39;</code></pre>
<pre><code>## Les objets suivants sont masqués depuis &#39;package:plyr&#39;:
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize</code></pre>
<pre><code>## Les objets suivants sont masqués depuis &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## Les objets suivants sont masqués depuis &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(dplyr)
group_by(my_data, group) %&gt;%
  summarise(
    count = n(),
    mean = mean(X8am, na.rm = TRUE),
    sd = sd(X8am, na.rm = TRUE)
  )</code></pre>
<pre><code>## # A tibble: 3 x 4
##   group count  mean    sd
##   &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1         7  124.  21.1
## 2 2         3  105.  14.0
## 3 &lt;NA&gt;      4  NaN   NA</code></pre>
<pre class="r"><code>library(&quot;ggpubr&quot;)</code></pre>
<pre><code>## 
## Attachement du package : &#39;ggpubr&#39;</code></pre>
<pre><code>## L&#39;objet suivant est masqué depuis &#39;package:plyr&#39;:
## 
##     mutate</code></pre>
<pre class="r"><code>ggboxplot(my_data, x = &quot;group&quot;, y = &quot;X8am&quot;, 
          color = &quot;group&quot;, palette = c(&quot;#00AFBB&quot;, &quot;#E7B800&quot;),
        ylab = &quot;X8am&quot;, xlab = &quot;Groups&quot;)</code></pre>
<pre><code>## Warning: Removed 4 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="practical4_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code># Shapiro-Wilk normality test for Men&#39;s weights
with(my_data, shapiro.test(X8am[group == &quot;1&quot;]))# p = 0.8698</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  X8am[group == &quot;1&quot;]
## W = 0.9662, p-value = 0.8698</code></pre>
<pre class="r"><code># Shapiro-Wilk normality test for Women&#39;s weights
with(my_data, shapiro.test(X8am[group == &quot;2&quot;])) # p = 0.4822</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  X8am[group == &quot;2&quot;]
## W = 0.92827, p-value = 0.4822</code></pre>
<p>From the output, the two p-values are greater than the significance level 0.05 implying that the distribution of the data are not significantly different from the normal distribution. In other words, we can assume the normality.</p>
<pre class="r"><code>res.ftest &lt;- var.test(X8am ~ group, data = my_data)
res.ftest</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  X8am by group
## F = 2.2782, num df = 6, denom df = 2, p-value = 0.6722
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##   0.05792299 16.53937046
## sample estimates:
## ratio of variances 
##           2.278195</code></pre>
<p>The p-value of F-test is p = 0.6722. It’s greater than the significance level alpha = 0.05. In conclusion, there is no significant difference between the variances of the two sets of data. Therefore, we can use the classic t-test witch assume equality of the two variances.</p>
<pre class="r"><code>res &lt;- t.test(X8am ~ group, data = my_data, var.equal = TRUE)
res</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  X8am by group
## t = 1.4604, df = 8, p-value = 0.1823
## alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
## 95 percent confidence interval:
##  -11.44319  50.96700
## sample estimates:
## mean in group 1 mean in group 2 
##        124.4286        104.6667</code></pre>
<p>The p-value of the test is 0.1823, which is above the significance level alpha = 0.05. We can conclude that the average concentration of group 1 is not significantly different from the average concentration of group 2 by one value. This is due to the fact that there is not enough data.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
